version: '3.8'
services:
  # Spring Boot
  backend:
    build: ./backend
    ports:
      - 8000:8000

  # MySQL
  database:
    image: mysql:8.0
    restart: always
    # Remove ports in prod
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=rolandgarros

  # phpMyAdmin
  database-explorer:
    image: phpmyadmin
    restart: always
    ports:
      - 8001:80
    environment:
      - PMA_HOST=database
      - PMA_USER=root
      - PMA_PASSWORD=root