FROM maven

# Create the app folder
RUN mkdir -p /app
WORKDIR /app

# Resolve dependencies
COPY pom.xml /app
RUN mvn -f /app/pom.xml dependency:resolve dependency:resolve-plugins

CMD ['maven', 'spring-boot:run']
